### ISSUE TITLE
Traefik network issue 

### ISSUE THREAD

**Issue by daemenseth** [andif888/workfromhome-with-docker#1]
I had one issue:
level=warning msg="Could not find network named 'traefik_proxy_net' for container '/guacamole-app'

I solved it to change line 38 in the docker compose from:
      - TRAEFIK_PROVIDERS_DOCKER_NETWORK=traefik_proxy_net
To:
- TRAEFIK_PROVIDERS_DOCKER_NETWORK=workfromhome-with-docker_proxy_net

**Comment by andif888** [comment]
Thank you!
