### ISSUE TITLE
Error on Installation, user another port

### ISSUE THREAD

**Issue by cybrpimp** [andif888/workfromhome-with-docker#2]
Got this error trying to install on Windows

![image](https://user-images.githubusercontent.com/61793417/94645977-c04be180-031f-11eb-9bac-8284c5431f40.png)

**Comment by andif888** [comment]
It seems you are running virtualbox on a host machine, which already has some kind of webserver installed, and the tcp port 443 is already in use. 
You have 2 different options to resolve for testing purpose:
1. Run it on a host machine, which do not have software installed, which uses already port 443.
2. Change line 24 in the Vagrantfile where it says `host: 443` to any unused tcp port. Maybe `host: 3443`.
